//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnigmaProject.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnigmaBase : DbContext
    {
        private static EnigmaBase context_;
        public EnigmaBase()
            : base("name=EnigmaBase")
        {
        }
        public static EnigmaBase GetContext()
        {
            if (context_ == null)
                context_ = new EnigmaBase();
            return context_;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EnigmaMachine> EnigmaMachines { get; set; }
        public virtual DbSet<Lesson> Lessons { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Quize> Quizes { get; set; }
        public virtual DbSet<Reflector> Reflectors { get; set; }
        public virtual DbSet<Rotor> Rotors { get; set; }
        public virtual DbSet<SetOfRotor> SetOfRotors { get; set; }
        public virtual DbSet<UserProgress> UserProgresses { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
