//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnigmaProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnigmaMachine
    {
        public int IdEnigmaMachine { get; set; }
        public Nullable<int> IdSetOfRotors { get; set; }
        public Nullable<int> IdReflector { get; set; }
    
        public virtual Reflector Reflector { get; set; }
        public virtual SetOfRotor SetOfRotor { get; set; }
    }
}
