//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnigmaApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rotor
    {
        public int IdRotor { get; set; }
        public Nullable<int> IdSetOfRotors { get; set; }
        public string Dictionary { get; set; }
    
        public virtual SetOfRotor SetOfRotor { get; set; }
    }
}
